from connection import get_connection, init_pool, release_connection


async def initialize_database():
    # Initialize pool first
    await init_pool()

    conn = await get_connection()

    try:
        await conn.execute("""
        CREATE TABLE IF NOT EXISTS Users(
            UserId TEXT PRIMARY KEY,
            UserName TEXT NOT NULL
        )
        """)

        await conn.execute("""
        CREATE TABLE IF NOT EXISTS Expenses(
            ExpenseId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            UserId TEXT NOT NULL,
            Amount REAL NOT NULL,
            Category TEXT NOT NULL,
            Description TEXT,
            ExpenseDate TEXT NOT NULL,
            CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(UserId)
            REFERENCES Users(UserId)
        )
        """)

        print("Database initialized with Neon Postgres")

    finally:
        await release_connection(conn)