from connection import get_connection


async def verify_write_access():
    conn = await get_connection()

    try:
        await conn.execute("""
        CREATE TABLE IF NOT EXISTS WriteTest(
            Id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
        )
        """)

        await conn.execute("""
        INSERT INTO WriteTest DEFAULT VALUES
        """)

        print("Database write access confirmed with Neon")

    finally:
        await conn.close()